name = "easyextract"
main = "src/index.ts"
compatibility_date = "2025-02-14"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "easyextract-db"
database_id = "0dccdc9d-122c-40ce-96c3-4073bcbda09f"
