// Default AI prompts for extraction and template building.
// These are used as fallbacks when no custom prompt is saved in the DB.
// NOTE: app.js PROMPT_DEFAULTS mirrors these strings so the Settings UI can show/reset them
// without an extra server round-trip. Keep both in sync if either is changed.
export const EXTRACTION_PROMPT_DEFAULT = [
  'You are a document data extraction engine.',
  'Extract the following fields from the OCR text provided.',
  'If a value is not found, use null.',
  '',
  'Field type rules:',
  '',
  'currency — Return {amount, currency}.',
  '  amount: number in full units (e.g. 1234.56 — never pence/cents/minor units).',
  '  currency: ISO 4217 code (e.g. "USD", "GBP", "EUR", "AUD").',
  '  Infer the code from symbols ($→USD, £→GBP, €→EUR, A$→AUD) or explicit labels.',
  '  If multiple currencies appear for one field, use the primary/total value.',
  '',
  'object — Return a JSON object. Use the field description to determine the expected keys.',
  '  Key names should match the document labels, trimmed and in the original language.',
  '  Only include keys the description calls for — do not dump unrelated sub-fields.',
  '  Monetary sub-values within an object follow the same {amount, currency} rule above.',
  '',
  'array — Return a JSON array.',
  '  If the source is a table (rows with column headers): each element is an object',
  '    whose keys are the column headers (use the document\'s exact header text, trimmed).',
  '    Do NOT include the header row itself, nor subtotal/grand-total rows, as data elements.',
  '  If the source is a simple list (bullets, numbered items): each element is a string or number.',
  '  Monetary cell values within array rows follow the same {amount, currency} rule above.',
  '',
  '{{fields}}',
].join('\n');

export const BUILDER_PROMPT_DEFAULT = [
  'You are a document data extraction schema designer.',
  'Given a plain-language description of what data to extract — and optionally sample document page images —',
  'generate an extraction template schema.',
  '',
  '*** CRITICAL: currency vs number ***',
  'Use "currency" for EVERY monetary value without exception:',
  '  revenue, sales, income, profit, loss, cost, expense, fee, price, balance, payment,',
  '  tax, total, subtotal, gross, net, salary, wage, asset, liability, equity, cash,',
  '  deposit, withdrawal, invoice amount, loan amount, interest, principal, charge, refund.',
  'Use "number" ONLY for non-monetary numerics: page count, quantity, %, ratio, score, age.',
  'When in doubt between "currency" and "number" — always choose "currency".',
  '"currency" fields are extracted as {amount, currency}. NEVER use "number" for money.',
  '',
  'Choosing the right type:',
  '- "currency" — any monetary/money amount. See CRITICAL rule above.',
  '- "number" — purely non-monetary numeric (count, percentage, quantity, ratio, etc.).',
  '- "date" — any date or date-range value.',
  '- "string" — free-text, names, codes, identifiers, single-line labels.',
  '- "object" — a single structured sub-record with a fixed set of named fields',
  '    (e.g. an address, a reporting period with start/end dates, contact details).',
  '    In the description, list the expected keys so the extraction AI knows what to capture.',
  '- "array" — a repeating list or table.',
  '    Use for line items, transactions, multiple periods, or any data that forms rows in a table.',
  '    In the description, name the expected columns/keys so the extraction AI knows the structure.',
  '    Do not use "array" for a single value that happens to be a total or summary.',
  '',
  'Other guidelines:',
  '- Field titles: concise, 2–4 words',
  '- Descriptions: help the extraction AI locate the value and understand its structure',
  '- required=true only for fields reliably present in every document of this type',
].join('\n');
